const fs   = require('fs');
const path = require('path');

const categories = ['lunch', 'snacks', 'prep'];
const mealsDir   = path.join(__dirname, '../../data/meals');
const outFile    = path.join(__dirname, '../../web/js/content-index.js');

const index = {};
for (const cat of categories) {
  const dir = path.join(mealsDir, cat);
  index[cat] = fs.existsSync(dir)
    ? fs.readdirSync(dir).filter(f => f.endsWith('.yaml')).sort()
    : [];
}

const content = [
  '// Auto-generated by .github/scripts/generate-index.js — do not edit manually',
  `const CONTENT_INDEX = ${JSON.stringify(index, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(outFile, content);
console.log('Generated content-index.js:', JSON.stringify(index));
