// Auto-generated by .github/scripts/generate-index.js — do not edit manually
const CONTENT_INDEX = {
  "lunch": [
    "beef-pasta-cremesauce.yaml",
    "cheeseburger-pfanne-mit-kartoffeln.yaml",
    "chili-con-carne.yaml",
    "couscous-salat-mariniertes-haehnchen.yaml",
    "griechischer-orzo-salat.yaml",
    "gruenkern-burger-bulgur-salat.yaml",
    "haehnchen-curry-mit-reis.yaml",
    "mozzarella-tomate-rucola-brot.yaml",
    "nudeln-linsen-hirtenkase.yaml",
    "rostbratwurst-griechischer-orzo-salat.yaml",
    "schupfnudel-rinderhack-pfanne.yaml"
  ],
  "snacks": [
    "gegrillte-karotten-hirtenkase.yaml",
    "jackfruit-tomate-toast.yaml",
    "tortilla-rohkost-tzatziki.yaml"
  ],
  "prep": [
    "pickled-ginger.yaml"
  ]
};
